local M = {}

---@param p NeothemePalette
---@return table<string, NeothemeHighlight>
function M.get(p)
	return {
		FzfLuaNormal = { link = "NormalFloat" },
		FzfLuaBorder = { link = "FloatBorder" },
		FzfLuaTitle = { link = "FloatTitle" },
		FzfLuaTitleFlags = { link = "CursorLine" },
		FzfLuaBackdrop = { bg = p.surface.deepest },
		FzfLuaPreviewNormal = { link = "NormalFloat" },
		FzfLuaPreviewBorder = { link = "FloatBorder" },
		FzfLuaPreviewTitle = { fg = p.ui.directory, bold = true },
		FzfLuaCursor = { link = "Cursor" },
		FzfLuaCursorLine = { link = "CursorLine" },
		FzfLuaCursorLineNr = { link = "CursorLineNr" },
		FzfLuaSearch = { link = "IncSearch" },
		FzfLuaScrollBorderEmpty = { fg = p.surface.border },
		FzfLuaScrollBorderFull = { fg = p.diagnostic.information },
		FzfLuaScrollFloatEmpty = { link = "PmenuSbar" },
		FzfLuaScrollFloatFull = { link = "PmenuThumb" },
		FzfLuaHelpNormal = { link = "NormalFloat" },
		FzfLuaHelpBorder = { link = "FloatBorder" },
		FzfLuaHeaderBind = { fg = p.ui.accent },
		FzfLuaHeaderText = { fg = p.syntax.comment },
		FzfLuaPathColNr = { fg = p.text.muted },
		FzfLuaPathLineNr = { fg = p.syntax.literal },
		FzfLuaBufName = { link = "Directory" },
		FzfLuaBufId = { link = "TabLine" },
		FzfLuaBufNr = { fg = p.syntax.literal },
		FzfLuaBufLineNr = { link = "LineNr" },
		FzfLuaBufFlagCur = { fg = p.ui.accent },
		FzfLuaBufFlagAlt = { fg = p.diagnostic.information },
		FzfLuaTabTitle = { fg = p.diagnostic.information },
		FzfLuaTabMarker = { fg = p.ui.accent },
		FzfLuaDirIcon = { link = "Directory" },
		FzfLuaDirPart = { link = "Comment" },
		FzfLuaFilePart = { fg = p.text.primary },
		FzfLuaLivePrompt = { fg = p.diagnostic.hint },
		FzfLuaLiveSym = { fg = p.diagnostic.hint },
		FzfLuaCmdEx = { link = "Statement" },
		FzfLuaCmdBuf = { link = "Added" },
		FzfLuaCmdGlobal = { link = "Directory" },
		FzfLuaFzfNormal = { link = "FzfLuaNormal" },
		FzfLuaFzfCursorLine = { link = "FzfLuaCursorLine" },
		FzfLuaFzfMatch = { fg = p.ui.search, bold = true },
		FzfLuaFzfBorder = { link = "FzfLuaBorder" },
		FzfLuaFzfScrollbar = { link = "FzfLuaFzfBorder" },
		FzfLuaFzfSeparator = { link = "FzfLuaFzfBorder" },
		FzfLuaFzfGutter = { link = "FzfLuaNormal" },
		FzfLuaFzfHeader = { link = "FzfLuaTitle" },
		FzfLuaFzfInfo = { link = "NonText" },
		FzfLuaFzfPointer = { fg = p.ui.accent },
		FzfLuaFzfMarker = { fg = p.diagnostic.success },
		FzfLuaFzfSpinner = { fg = p.diagnostic.hint },
		FzfLuaFzfPrompt = { fg = p.diagnostic.information },
		FzfLuaFzfQuery = { link = "FzfLuaNormal" },
	}
end

return M
