local M = {}

---@param p NeothemePalette
---@return table<string, NeothemeHighlight>
function M.get(p)
	return {
		SnacksDashboardNormal = { link = "Normal" },
		SnacksDashboardDesc = { fg = p.text.bright },
		SnacksDashboardFile = { fg = p.text.primary },
		SnacksDashboardDir = { fg = p.text.muted },
		SnacksDashboardFooter = { fg = p.syntax.comment, italic = true },
		SnacksDashboardHeader = { fg = p.diagnostic.information },
		SnacksDashboardIcon = { fg = p.ui.accent },
		SnacksDashboardKey = { fg = p.diagnostic.hint },
		SnacksDashboardSpecial = { fg = p.diagnostic.success },
		SnacksDashboardTitle = { fg = p.ui.accent, bold = true },

		SnacksIndent = { fg = p.surface.border },
		SnacksIndentScope = { fg = p.syntax.comment },
		SnacksIndentChunk = { fg = p.syntax.property },

		SnacksInputNormal = { link = "NormalFloat" },
		SnacksInputBorder = { link = "FloatBorder" },
		SnacksInputTitle = { link = "FloatTitle" },
		SnacksInputIcon = { fg = p.diagnostic.information },

		SnacksNotifierInfo = { link = "DiagnosticInfo" },
		SnacksNotifierWarn = { link = "DiagnosticWarn" },
		SnacksNotifierError = { link = "DiagnosticError" },
		SnacksNotifierDebug = { fg = p.text.muted },
		SnacksNotifierTrace = { fg = p.diagnostic.hint },
		SnacksNotifierBorderInfo = { link = "DiagnosticInfo" },
		SnacksNotifierBorderWarn = { link = "DiagnosticWarn" },
		SnacksNotifierBorderError = { link = "DiagnosticError" },
		SnacksNotifierBorderDebug = { fg = p.text.muted },
		SnacksNotifierBorderTrace = { fg = p.diagnostic.hint },
		SnacksNotifierTitleInfo = { link = "DiagnosticInfo" },
		SnacksNotifierTitleWarn = { link = "DiagnosticWarn" },
		SnacksNotifierTitleError = { link = "DiagnosticError" },
		SnacksNotifierTitleDebug = { fg = p.text.muted },
		SnacksNotifierTitleTrace = { fg = p.diagnostic.hint },
		SnacksNotifierIconInfo = { link = "DiagnosticInfo" },
		SnacksNotifierIconWarn = { link = "DiagnosticWarn" },
		SnacksNotifierIconError = { link = "DiagnosticError" },
		SnacksNotifierIconDebug = { fg = p.text.muted },
		SnacksNotifierIconTrace = { fg = p.diagnostic.hint },

		SnacksPicker = { fg = p.text.primary, bg = p.surface.dark },
		SnacksPickerBorder = { fg = p.surface.border, bg = p.surface.dark },
		SnacksPickerTitle = { fg = p.ui.accent, bold = true },
		SnacksPickerMatch = { fg = p.ui.search, bold = true },
		SnacksPickerCursorLine = { link = "CursorLine" },
		SnacksPickerDir = { fg = p.text.muted },
		SnacksPickerFile = { fg = p.text.bright },
		SnacksPickerPathHidden = { fg = p.version_control.ignored },
		SnacksPickerPathIgnored = { fg = p.version_control.ignored, italic = true },
		SnacksPickerTotals = { fg = p.text.muted },
		SnacksPickerPrompt = { fg = p.diagnostic.information },
		SnacksPickerInput = { fg = p.text.primary, bg = p.surface.raised },
		SnacksPickerInputBorder = { fg = p.surface.border, bg = p.surface.raised },
		SnacksPickerInputTitle = { fg = p.ui.accent },
		SnacksPickerList = { fg = p.text.primary, bg = p.surface.dark },
		SnacksPickerListBorder = { fg = p.surface.border, bg = p.surface.dark },
		SnacksPickerListTitle = { fg = p.diagnostic.success },
		SnacksPickerPreview = { fg = p.text.primary, bg = p.surface.base },
		SnacksPickerPreviewBorder = { fg = p.surface.border, bg = p.surface.base },
		SnacksPickerPreviewTitle = { fg = p.diagnostic.information },
		SnacksPickerBoxTitle = { fg = p.ui.accent },
		SnacksPickerToggle = { fg = p.diagnostic.hint },
		SnacksPickerDimmed = { fg = p.surface.muted },
		SnacksPickerIdx = { fg = p.syntax.literal },
		SnacksPickerRow = { fg = p.syntax.literal },
		SnacksPickerCol = { fg = p.text.muted },
		SnacksPickerTree = { fg = p.surface.muted },
		SnacksPickerGitStatusAdded = { link = "Added" },
		SnacksPickerGitStatusModified = { link = "Changed" },
		SnacksPickerGitStatusDeleted = { link = "Removed" },
		SnacksPickerGitStatusUntracked = { link = "Added" },
		SnacksPickerGitStatusIgnored = { fg = p.version_control.ignored },
		SnacksPickerGitStatusRenamed = { fg = p.diagnostic.hint },
		SnacksPickerGitStatusCopied = { fg = p.version_control.added },
		SnacksPickerGitStatusUnmerged = { fg = p.version_control.conflict },

		SnacksProfilerIconInfo = { fg = p.diagnostic.information },
		SnacksProfilerBadgeInfo = { fg = p.text.on_accent, bg = p.diagnostic.information },
		SnacksProfilerIconTrace = { fg = p.diagnostic.hint },
		SnacksProfilerBadgeTrace = { fg = p.text.on_accent, bg = p.diagnostic.hint },
		SnacksProfilerLoc = { fg = p.text.muted },
		SnacksProfilerSrc = { fg = p.text.bright },
		SnacksProfilerTime = { fg = p.diagnostic.warning },
		SnacksProfilerPlugin = { fg = p.diagnostic.success },

		SnacksScratchKey = { fg = p.ui.accent },
		SnacksScratchDesc = { fg = p.text.bright },
		SnacksScratchFile = { fg = p.ui.directory },
		SnacksStatusColumnMark = { fg = p.ui.accent },
		SnacksStatusColumnFold = { fg = p.syntax.comment },
		SnacksWordsEnabled = { fg = p.diagnostic.success },
		SnacksWordsDisabled = { fg = p.diagnostic.error },
		SnacksZenIcon = { fg = p.diagnostic.hint },
	}
end

return M
