local M = {}

---@param p NeothemePalette
---@return table<string, NeothemeHighlight>
function M.get(p)
	return {
		TroubleNormal = { fg = p.text.primary, bg = p.surface.dark },
		TroubleNormalNC = { fg = p.text.primary, bg = p.surface.dark },
		TroubleText = { fg = p.text.primary },
		TroubleTextError = { link = "TroubleText" },
		TroubleTextWarning = { link = "TroubleText" },
		TroubleTextInformation = { link = "TroubleText" },
		TroubleTextHint = { link = "TroubleText" },
		TroubleSignError = { link = "DiagnosticError" },
		TroubleSignWarning = { link = "DiagnosticWarn" },
		TroubleSignInformation = { link = "DiagnosticInfo" },
		TroubleSignHint = { link = "DiagnosticHint" },
		TroubleSignOther = { link = "DiagnosticInfo" },
		TroubleError = { link = "DiagnosticError" },
		TroubleWarning = { link = "DiagnosticWarn" },
		TroubleInformation = { link = "DiagnosticInfo" },
		TroubleHint = { link = "DiagnosticHint" },
		TroubleCount = { fg = p.diagnostic.hint, bold = true },
		TroubleIndent = { fg = p.surface.border },
		TroubleLocation = { fg = p.text.muted },
		TroubleFile = { fg = p.ui.directory },
		TroubleSource = { fg = p.text.muted },
		TroubleCode = { fg = p.syntax.literal },
		TroubleFoldIcon = { fg = p.syntax.comment },
		TroublePreview = { bg = p.surface.selected },
		TroublePos = { fg = p.syntax.literal },
		TroubleDirectory = { link = "Directory" },
		TroubleIconDirectory = { link = "Directory" },
		TroubleIconArray = { link = "@punctuation.bracket" },
		TroubleIconBoolean = { link = "Boolean" },
		TroubleIconClass = { link = "Type" },
		TroubleIconConstant = { link = "Constant" },
		TroubleIconConstructor = { link = "@constructor" },
		TroubleIconEnum = { link = "Type" },
		TroubleIconEnumMember = { link = "Constant" },
		TroubleIconEvent = { fg = p.syntax.comment },
		TroubleIconField = { link = "@variable.member" },
		TroubleIconFile = { fg = p.text.bright },
		TroubleIconFunction = { link = "Function" },
		TroubleIconInterface = { link = "Type" },
		TroubleIconKey = { link = "@property" },
		TroubleIconMethod = { link = "@function.method" },
		TroubleIconModule = { link = "@module" },
		TroubleIconNamespace = { link = "@module" },
		TroubleIconNull = { link = "Constant" },
		TroubleIconNumber = { link = "Number" },
		TroubleIconObject = { link = "Type" },
		TroubleIconOperator = { link = "Operator" },
		TroubleIconPackage = { link = "@module" },
		TroubleIconProperty = { link = "@property" },
		TroubleIconString = { link = "String" },
		TroubleIconStruct = { link = "Structure" },
		TroubleIconTypeParameter = { link = "@type.definition" },
		TroubleIconVariable = { link = "Identifier" },
	}
end

return M
