local M = {}

---@param options NeothemeOptions
---@param p NeothemePalette
---@return table<string, NeothemeHighlight>
function M.get(options, p)
	local groups = {
		NeothemeText = { fg = p.text.primary },
		NeothemeTextBright = { fg = p.text.bright },
		NeothemeTextStrong = { fg = p.text.strong, bold = options.bold },
		NeothemeTextMuted = { fg = p.text.muted },
		NeothemeSurfaceDark = { bg = p.surface.dark },
		NeothemeSurface = { bg = p.surface.base },
		NeothemeSurfaceRaised = { bg = p.surface.raised },
		NeothemeSurfaceSelected = { bg = p.surface.selected },
		NeothemeBorder = { fg = p.surface.border },
		NeothemeComment = { fg = p.syntax.comment, italic = options.italic.comments },
		NeothemeString = { fg = p.syntax.string, italic = options.italic.strings },
		NeothemeKeyword = { fg = p.syntax.keyword, bold = options.bold },
		NeothemeFunction = { fg = p.syntax.function_name },
		NeothemeNumber = { fg = p.syntax.literal },
		NeothemeType = { fg = p.syntax.type },
		NeothemeProperty = { fg = p.syntax.property },
		NeothemeOperator = { fg = p.syntax.operator, italic = options.italic.operators },
		NeothemePunctuation = { fg = p.syntax.punctuation },
		NeothemeError = { fg = p.diagnostic.error, bold = options.bold },
		NeothemeWarning = { fg = p.diagnostic.warning, bold = options.bold },
		NeothemeInformation = { fg = p.diagnostic.information, bold = options.bold },
		NeothemeHint = { fg = p.diagnostic.hint },
		NeothemeSuccess = { fg = p.diagnostic.success, bold = options.bold },
		NeothemeAdded = { fg = p.version_control.added },
		NeothemeChanged = { fg = p.version_control.changed },
		NeothemeRemoved = { fg = p.version_control.removed },

		Comment = { link = "NeothemeComment" },
		Constant = { link = "NeothemeNumber" },
		String = { link = "NeothemeString" },
		Character = { link = "NeothemeString" },
		Number = { link = "NeothemeNumber" },
		Boolean = { link = "NeothemeNumber" },
		Float = { link = "NeothemeNumber" },
		Identifier = { fg = p.text.primary },
		Function = { link = "NeothemeFunction" },
		Statement = { link = "NeothemeKeyword" },
		Conditional = { link = "NeothemeKeyword" },
		Repeat = { link = "NeothemeKeyword" },
		Label = { fg = p.syntax.function_name },
		Operator = { link = "NeothemeOperator" },
		Keyword = { link = "NeothemeKeyword" },
		Exception = { fg = p.diagnostic.error, bold = options.bold },
		PreProc = { fg = p.syntax.comment },
		Include = { fg = p.syntax.function_name },
		Define = { fg = p.syntax.keyword },
		Macro = { fg = p.syntax.literal },
		PreCondit = { fg = p.syntax.keyword },
		Type = { link = "NeothemeType" },
		StorageClass = { fg = p.syntax.keyword },
		Structure = { link = "NeothemeType" },
		Typedef = { link = "NeothemeType" },
		Special = { fg = p.syntax.special },
		SpecialChar = { fg = p.syntax.special },
		Tag = { fg = p.syntax.tag },
		Delimiter = { link = "NeothemePunctuation" },
		SpecialComment = { link = "NeothemeComment" },
		Debug = { fg = p.diagnostic.error },
		Underlined = { fg = p.diagnostic.information, underline = options.underline },
		Ignore = { fg = p.version_control.ignored },
		Error = { link = "NeothemeError" },
		Todo = { fg = p.diagnostic.warning, bold = options.bold },
		Added = { link = "NeothemeAdded" },
		Changed = { link = "NeothemeChanged" },
		Removed = { link = "NeothemeRemoved" },

		Normal = { fg = p.text.primary, bg = p.surface.base },
		NormalNC = { fg = p.text.primary, bg = p.surface.base },
		ColorColumn = { bg = p.surface.raised },
		Conceal = { fg = p.text.muted, bg = p.surface.base },
		CurSearch = { fg = p.text.on_accent, bg = p.ui.current_search, bold = options.bold },
		Cursor = { fg = p.text.on_accent, bg = p.ui.cursor },
		lCursor = { link = "Cursor" },
		CursorIM = { link = "Cursor" },
		CursorColumn = { bg = p.surface.raised },
		CursorLine = { bg = p.surface.raised },
		Directory = { fg = p.ui.directory, bold = options.bold },
		DiffAdd = { fg = p.version_control.added, bg = p.surface.addition },
		DiffChange = { fg = p.version_control.changed, bg = p.surface.raised },
		DiffDelete = { fg = p.version_control.removed, bg = p.surface.raised },
		DiffText = { fg = p.text.strong, bg = p.surface.selected, bold = options.bold },
		DiffTextAdd = { fg = p.version_control.added, bg = p.surface.selected, bold = options.bold },
		EndOfBuffer = { fg = p.surface.muted },
		TermCursor = { link = "Cursor" },
		OkMsg = { link = "NeothemeSuccess" },
		WarningMsg = { link = "NeothemeWarning" },
		ErrorMsg = { fg = p.text.on_error, bg = p.surface.error, bold = options.bold },
		StderrMsg = { link = "NeothemeError" },
		StdoutMsg = { link = "NeothemeTextBright" },
		WinSeparator = { fg = p.surface.border, bg = p.surface.base },
		Folded = { fg = p.syntax.comment, bg = p.surface.raised, italic = options.italic.folds },
		FoldColumn = { fg = p.syntax.comment, bg = p.surface.dark },
		SignColumn = { fg = p.surface.muted, bg = p.surface.base },
		IncSearch = { fg = p.text.on_accent, bg = p.ui.match, bold = options.bold },
		Substitute = { fg = p.text.on_error, bg = p.version_control.conflict },
		LineNr = { fg = p.surface.muted },
		LineNrAbove = { fg = p.surface.muted },
		LineNrBelow = { fg = p.surface.muted },
		CursorLineNr = { fg = p.ui.accent, bold = options.bold },
		CursorLineFold = { fg = p.syntax.comment, bg = p.surface.raised },
		CursorLineSign = { fg = p.ui.accent, bg = p.surface.raised },
		MatchParen = { fg = p.text.on_accent, bg = p.ui.match, bold = options.bold },
		ModeMsg = { link = "NeothemeSuccess" },
		MsgArea = { fg = p.text.primary, bg = p.surface.base },
		MsgSeparator = { fg = p.surface.border, bg = p.surface.raised },
		MoreMsg = { fg = p.diagnostic.information },
		NonText = { fg = p.surface.muted },
		NormalFloat = { fg = p.text.primary, bg = p.surface.raised },
		FloatBorder = { fg = p.surface.border, bg = p.surface.raised },
		FloatShadow = { bg = p.surface.deepest, blend = 60 },
		FloatShadowThrough = { bg = p.surface.deepest, blend = 80 },
		FloatTitle = { fg = p.ui.accent, bg = p.surface.raised, bold = options.bold },
		FloatFooter = { fg = p.text.muted, bg = p.surface.raised },
		Pmenu = { fg = p.text.primary, bg = p.surface.raised },
		PmenuSel = { fg = p.text.strong, bg = p.surface.selected },
		PmenuKind = { fg = p.syntax.function_name, bg = p.surface.raised },
		PmenuKindSel = { fg = p.syntax.function_name, bg = p.surface.selected },
		PmenuExtra = { fg = p.text.muted, bg = p.surface.raised },
		PmenuExtraSel = { fg = p.text.muted, bg = p.surface.selected },
		PmenuSbar = { bg = p.surface.dark },
		PmenuThumb = { bg = p.surface.muted },
		PmenuMatch = { fg = p.ui.search, bg = p.surface.raised, bold = options.bold },
		PmenuMatchSel = { fg = p.ui.search, bg = p.surface.selected, bold = options.bold },
		PmenuBorder = { fg = p.surface.border, bg = p.surface.raised },
		PmenuShadow = { bg = p.surface.deepest, blend = 60 },
		PmenuShadowThrough = { bg = p.surface.deepest, blend = 80 },
		ComplMatchIns = { link = "PmenuMatch" },
		PreInsert = { fg = p.syntax.literal, italic = true },
		ComplHint = { fg = p.text.muted, italic = true },
		ComplHintMore = { fg = p.syntax.property, italic = true },
		Question = { fg = p.diagnostic.information, bold = options.bold },
		QuickFixLine = { bg = p.surface.selected, bold = options.bold },
		Search = { fg = p.text.on_accent, bg = p.ui.search },
		SnippetTabstop = { fg = p.text.bright, bg = p.surface.selected },
		SnippetTabstopActive = { fg = p.text.on_accent, bg = p.ui.accent, bold = options.bold },
		SpecialKey = { fg = p.text.muted },
		SpellBad = { sp = p.diagnostic.error, undercurl = options.undercurl },
		SpellCap = { sp = p.diagnostic.warning, undercurl = options.undercurl },
		SpellLocal = { sp = p.diagnostic.information, undercurl = options.undercurl },
		SpellRare = { sp = p.diagnostic.hint, undercurl = options.undercurl },
		StatusLine = { fg = p.text.strong, bg = p.surface.selected, bold = options.bold },
		StatusLineNC = { fg = p.text.muted, bg = p.surface.dark },
		StatusLineTerm = { fg = p.text.on_accent, bg = p.diagnostic.success, bold = options.bold },
		StatusLineTermNC = { fg = p.text.muted, bg = p.surface.dark },
		TabLine = { fg = p.text.muted, bg = p.surface.dark },
		TabLineFill = { fg = p.surface.muted, bg = p.surface.dark },
		TabLineSel = { fg = p.text.strong, bg = p.surface.raised, bold = options.bold },
		Title = { fg = p.ui.accent, bold = options.bold },
		Visual = { bg = p.surface.selected },
		VisualNOS = { bg = p.surface.raised },
		Whitespace = { fg = p.surface.muted },
		WildMenu = { fg = p.text.on_accent, bg = p.ui.accent, bold = options.bold },
		WinBar = { fg = p.text.bright, bg = p.surface.raised, bold = options.bold },
		WinBarNC = { fg = p.text.muted, bg = p.surface.dark },
		Menu = { fg = p.text.primary, bg = p.surface.raised },
		Scrollbar = { fg = p.surface.muted, bg = p.surface.dark },
		Tooltip = { fg = p.text.primary, bg = p.surface.raised },

		User1 = { fg = p.ui.accent, bg = p.surface.selected, bold = options.bold },
		User2 = { fg = p.diagnostic.success, bg = p.surface.selected },
		User3 = { fg = p.diagnostic.hint, bg = p.surface.selected },
		User4 = { fg = p.diagnostic.error, bg = p.surface.selected },
		User5 = { fg = p.diagnostic.information, bg = p.surface.selected },
		User6 = { fg = p.syntax.comment, bg = p.surface.selected },
		User7 = { fg = p.text.muted, bg = p.surface.selected },
		User8 = { fg = p.text.bright, bg = p.surface.selected },
		User9 = { fg = p.text.strong, bg = p.surface.selected, bold = options.bold },

		RedrawDebugNormal = { reverse = true },
		RedrawDebugClear = { fg = p.text.on_accent, bg = p.diagnostic.warning },
		RedrawDebugComposed = { fg = p.text.on_accent, bg = p.diagnostic.success },
		RedrawDebugRecompose = { fg = p.text.on_accent, bg = p.diagnostic.error },

		NeothemeSidebar = { fg = p.text.primary, bg = p.surface.dark },
		NeothemeSidebarSign = { fg = p.surface.muted, bg = p.surface.dark },
		qfFileName = { fg = p.ui.directory },
		qfSeparator1 = { fg = p.surface.muted },
		qfLineNr = { fg = p.syntax.literal },
		qfSeparator2 = { fg = p.surface.muted },
		qfText = { fg = p.text.primary },
		qfError = { link = "DiagnosticError" },
		qfWarning = { link = "DiagnosticWarn" },
		qfNote = { link = "DiagnosticHint" },
		qfInfo = { link = "DiagnosticInfo" },
	}

	return groups
end

return M
